# Generated by Django 4.2.7 on 2026-03-21 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начисления')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('deals_count', models.IntegerField(default=0, verbose_name='Оформлено сделок за день')),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Объём кредитов за день')),
                ('additional_products', models.IntegerField(default=0, verbose_name='Оформлено доп. продуктов')),
            ],
            options={
                'verbose_name': 'Результат дня',
                'verbose_name_plural': 'Результаты дня',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата сделки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма кредита')),
                ('additional_products', models.IntegerField(default=0, verbose_name='Количество доп. продуктов')),
                ('is_financed', models.BooleanField(default=True, verbose_name='Профинансировано')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('min_points', models.FloatField(verbose_name='Минимальное количество баллов')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('financial_effect', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Финансовый эффект (руб/год)')),
                ('mortgage_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Экономия по ипотеке')),
                ('cashback', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Кэшбэк')),
                ('insurance_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость ДМС')),
                ('badge_image', models.ImageField(blank=True, upload_to='badges/', verbose_name='Изображение бейджа')),
                ('color_code', models.CharField(default='#C0C0C0', max_length=20, verbose_name='Цветовой код')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'ordering': ['min_points'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('financial_effect', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Финансовый эффект (руб)')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('locked', 'Заблокирована'), ('upcoming', 'Откроется при след. уровне')], default='locked', max_length=20, verbose_name='Статус')),
                ('icon', models.ImageField(blank=True, upload_to='privileges/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Привилегия',
                'verbose_name_plural': 'Привилегии',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата расчёта')),
                ('total_points', models.FloatField(default=0, verbose_name='Общее количество баллов')),
                ('volume_points', models.FloatField(default=0, verbose_name='Баллы за объём')),
                ('deals_points', models.FloatField(default=0, verbose_name='Баллы за сделки')),
                ('share_points', models.FloatField(default=0, verbose_name='Баллы за долю банка')),
                ('dealer_rank', models.IntegerField(blank=True, null=True, verbose_name='Место внутри дилера')),
                ('region_rank', models.IntegerField(blank=True, null=True, verbose_name='Место в регионе')),
                ('global_rank', models.IntegerField(blank=True, null=True, verbose_name='Место в общем рейтинге')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ['-date', '-total_points'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_from_support', models.BooleanField(default=False, verbose_name='От поддержки')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('admin_response', models.TextField(blank=True, verbose_name='Ответ администратора')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('task_type', models.CharField(choices=[('deal', 'Сделка'), ('volume', 'Объём'), ('share', 'Доля банка'), ('product', 'Доп. продукт')], max_length=20, verbose_name='Тип задачи')),
                ('target_value', models.FloatField(verbose_name='Целевое значение')),
                ('reward_points', models.FloatField(verbose_name='Награда (баллы)')),
                ('deadline_days', models.IntegerField(default=30, verbose_name='Дедлайн (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_video', models.BooleanField(default=False, verbose_name='Видеоурок')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('content', models.TextField(blank=True, verbose_name='Текст материала')),
                ('reward_points', models.FloatField(default=10, verbose_name='Баллы за прохождение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Обучающий модуль',
                'verbose_name_plural': 'Обучающие модули',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('correct_answer', models.CharField(max_length=500, verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы тестов',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.FloatField(default=0, verbose_name='Текущее значение')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Выполнена'), ('expired', 'Просрочена')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
            ],
            options={
                'verbose_name': 'Задача пользователя',
                'verbose_name_plural': 'Задачи пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прохождения')),
                ('test_score', models.IntegerField(default=0, verbose_name='Результат теста')),
                ('earned_points', models.FloatField(default=0, verbose_name='Получено баллов')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trainings', to='core.trainingmodule')),
            ],
            options={
                'verbose_name': 'Обучение пользователя',
                'verbose_name_plural': 'Обучение пользователей',
            },
        ),
    ]
