# Generated by Django 4.2.7 on 2026-03-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('financial_effect_rub', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Финансовый эффект в рублях')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('gold_locked', 'Откроется при Gold'), ('platinum_locked', 'Откроется при Platinum')], default='gold_locked', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Привилегия уровня',
                'verbose_name_plural': 'Привилегии уровня',
            },
        ),
    ]
