# Generated by Django 4.2.7 on 2026-03-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilege',
            name='status',
        ),
        migrations.AddField(
            model_name='privilege',
            name='role',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='silver', max_length=20, verbose_name='Роль'),
        ),
    ]
