# Generated by Django 4.2.7 on 2026-03-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_privilege_status_privilege_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='name',
            field=models.CharField(default='Название', max_length=200, verbose_name='Название'),
        ),
    ]
