# Generated by Django 4.2.7 on 2026-03-21 10:34

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('dealer_code', models.CharField(blank=True, max_length=50, verbose_name='Код ДЦ')),
                ('position', models.CharField(choices=[('cso', 'КСО'), ('manager', 'Менеджер'), ('rop', 'РОП'), ('director', 'Директор')], default='manager', max_length=20, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('level', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('black', 'Black')], default='silver', max_length=20, verbose_name='Уровень привилегии')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('sber_id', models.CharField(blank=True, max_length=100, verbose_name='Sber ID')),
                ('volume_points', models.FloatField(default=0, verbose_name='Баллы за объём')),
                ('deals_points', models.FloatField(default=0, verbose_name='Баллы за сделки')),
                ('share_points', models.FloatField(default=0, verbose_name='Баллы за долю банка')),
                ('total_deals', models.IntegerField(default=0, verbose_name='Всего сделок')),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общий объём')),
                ('bank_share', models.FloatField(default=0, verbose_name='Доля банка в портфеле')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('block_reason', models.TextField(blank=True, verbose_name='Причина блокировки')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
