# Generated by Django 4.2.7 on 2026-03-21 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deals_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='share_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='volume_points',
        ),
        migrations.AddField(
            model_name='user',
            name='current_month_points',
            field=models.FloatField(default=0, verbose_name='Баллы за текущий месяц'),
        ),
        migrations.CreateModel(
            name='MonthlyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц (1-12)')),
                ('volume_index', models.FloatField(verbose_name='Индекс объёма (0-120)')),
                ('deals_index', models.FloatField(verbose_name='Индекс количества сделок (0-120)')),
                ('share_index', models.FloatField(verbose_name='Индекс доли банка (0-120)')),
                ('conversion_index', models.FloatField(verbose_name='Индекс конверсии (0-120)')),
                ('total_points', models.FloatField(verbose_name='Итоговые баллы (0-120)')),
                ('level', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('black', 'Black')], max_length=20, verbose_name='Уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчёта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Месячный рейтинг',
                'verbose_name_plural': 'Месячные рейтинги',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата подачи')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='last_month_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.monthlyrating'),
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц (1-12)')),
                ('volume_plan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='План по объёму (млн ₽)')),
                ('deals_plan', models.IntegerField(default=0, verbose_name='План по количеству сделок')),
                ('target_share', models.FloatField(default=50, verbose_name='Целевая доля банка (%)')),
                ('conversion_plan', models.FloatField(default=70, verbose_name='План по конверсии (%)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Месячный план',
                'verbose_name_plural': 'Месячные планы',
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
