# Generated by Django 4.2.7 on 2026-03-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deals_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='share_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_deals',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_volume',
        ),
        migrations.RemoveField(
            model_name='user',
            name='volume_points',
        ),
        migrations.AddField(
            model_name='user',
            name='bank_share_plan',
            field=models.FloatField(default=50, verbose_name='Доля банка в портфеле'),
        ),
        migrations.AddField(
            model_name='user',
            name='conversion_rate',
            field=models.IntegerField(default=0, verbose_name='Конверсия'),
        ),
        migrations.AddField(
            model_name='user',
            name='conversion_rate_plan',
            field=models.IntegerField(default=70, verbose_name='Конверсия'),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_transactions',
            field=models.FloatField(default=0, verbose_name='Количество сделок'),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_transactions_plan',
            field=models.FloatField(default=10, verbose_name='Количество сделок'),
        ),
        migrations.AddField(
            model_name='user',
            name='volume_of_transactions',
            field=models.FloatField(default=0, verbose_name='Объём сделок в рублях'),
        ),
        migrations.AddField(
            model_name='user',
            name='volume_of_transactions_plan',
            field=models.FloatField(default=10, verbose_name='Объём сделок в рублях'),
        ),
    ]
