# Generated by Django 4.2.7 on 2026-03-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_deals_points_remove_user_share_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_share_plan',
            field=models.FloatField(default=50, verbose_name='Доля банка в портфеле ПЛАН'),
        ),
        migrations.AlterField(
            model_name='user',
            name='conversion_rate_plan',
            field=models.IntegerField(default=70, verbose_name='Конверсия ПЛАН'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_transactions_plan',
            field=models.FloatField(default=10, verbose_name='Количество сделок ПЛАН'),
        ),
        migrations.AlterField(
            model_name='user',
            name='volume_of_transactions_plan',
            field=models.FloatField(default=10, verbose_name='Объём сделок в рублях ПЛАН'),
        ),
    ]
