# Generated by Django 4.2.7 on 2026-03-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_bank_share_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.FloatField(default=0, verbose_name='Итого баллов'),
        ),
    ]
