# Generated by Django 4.2.7 on 2026-03-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_points',
            field=models.FloatField(default=0, editable=False, verbose_name='Итого баллов'),
        ),
    ]
