# Generated by Django 4.2.7 on 2026-03-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_level_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления уровня'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_points',
            field=models.FloatField(default=0, verbose_name='Итого баллов'),
        ),
    ]
