# Generated by Django 4.2.7 on 2026-03-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_last_level_update_alter_user_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_points',
        ),
    ]
