# Generated by Django 4.2.7 on 2026-03-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('black', 'Platinum')], default='silver', max_length=20, verbose_name='Уровень привилегии'),
        ),
    ]
