# Generated by Django 4.2.7 on 2026-03-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('silver', 'silver'), ('gold', 'gold'), ('platinum', 'platinum')], default='silver', max_length=20, verbose_name='Уровень привилегии'),
        ),
    ]
