# Generated by Django 4.2.7 on 2026-03-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_level_update',
            new_name='last_status_update',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='level',
            new_name='status',
        ),
    ]
