# Generated by Django 4.2.7 on 2026-03-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_last_level_update_user_last_status_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='block_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
    ]
