# Generated by Django 4.2.7 on 2026-03-21 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_block_reason_remove_user_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
    ]
