# Generated by Django 4.2.7 on 2026-03-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conversion_points',
            field=models.FloatField(default=0, verbose_name='Баллы за конверсию'),
        ),
        migrations.AddField(
            model_name='user',
            name='deals_points',
            field=models.FloatField(default=0, verbose_name='Баллы за количество сделок'),
        ),
        migrations.AddField(
            model_name='user',
            name='share_points',
            field=models.FloatField(default=0, verbose_name='Баллы за долю банка'),
        ),
        migrations.AddField(
            model_name='user',
            name='volume_points',
            field=models.FloatField(default=0, verbose_name='Баллы за объём сделок'),
        ),
    ]
