# Generated by Django 4.2.7 on 2026-03-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_conversion_points_user_deals_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='volume_of_transactions',
            field=models.FloatField(default=0, verbose_name='Объём сделок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='volume_of_transactions_plan',
            field=models.FloatField(default=10, verbose_name='Объём сделок ПЛАН'),
        ),
    ]
