# Generated by Django 4.2.7 on 2026-03-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_volume_of_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='conversion_points',
            field=models.IntegerField(default=0, verbose_name='Баллы за конверсию'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deals_points',
            field=models.IntegerField(default=0, verbose_name='Баллы за количество сделок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='share_points',
            field=models.IntegerField(default=0, verbose_name='Баллы за долю банка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='volume_points',
            field=models.IntegerField(default=0, verbose_name='Баллы за объём сделок'),
        ),
    ]
