# Generated by Django 4.2.7 on 2026-03-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_conversion_points_alter_user_deals_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='conversion_rate',
            field=models.IntegerField(default=0, verbose_name='Одобрено заявок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='conversion_rate_plan',
            field=models.IntegerField(default=70, verbose_name='Подано заявок'),
        ),
    ]
