# Generated by Django 4.2.7 on 2026-03-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_conversion_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='months_gold_current_year',
            field=models.IntegerField(default=0, verbose_name='Месяцев в статусе Gold в текущем году'),
        ),
        migrations.AddField(
            model_name='user',
            name='months_platinum_current_year',
            field=models.IntegerField(default=0, verbose_name='Месяцев в статусе Platinum в текущем году'),
        ),
        migrations.AddField(
            model_name='user',
            name='months_silver_current_year',
            field=models.IntegerField(default=0, verbose_name='Месяцев в статусе Silver в текущем году'),
        ),
    ]
