# Generated by Django 4.2.7 on 2026-03-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_months_gold_current_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_points_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления баллов'),
        ),
    ]
