# Generated by Django 4.2.7 on 2026-03-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_last_points_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_points_update',
        ),
    ]
