# Generated by Django 4.2.7 on 2026-03-22 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_user_last_points_update'),
        ('users', '0019_user_financial_fields_and_monthly_tracking'),
    ]

    operations = [
    ]
