# Generated by Django 4.2.7 on 2026-03-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_20260322_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bonus_income_yearly_rub',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cashback_yearly_rub',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dms_yearly_rub',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mortgage_savings_yearly_rub',
        ),
    ]
