# Generated by Django 4.2.7 on 2026-03-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_user_bonus_income_yearly_rub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_income_yearly_rub',
            field=models.PositiveIntegerField(default=0, verbose_name='Доп. доход от бонусов за год (₽)'),
        ),
        migrations.AddField(
            model_name='user',
            name='cashback_yearly_rub',
            field=models.PositiveIntegerField(default=0, verbose_name='Кэшбэк за год (₽)'),
        ),
        migrations.AddField(
            model_name='user',
            name='dms_yearly_rub',
            field=models.PositiveIntegerField(default=0, verbose_name='ДМС стоимость за год (₽)'),
        ),
        migrations.AddField(
            model_name='user',
            name='mortgage_savings_yearly_rub',
            field=models.PositiveIntegerField(default=0, verbose_name='Экономия по ипотеке за год (₽)'),
        ),
    ]
